$(document).ready(function(){
    $("button").click(function(){
        $("p").toggle();
    });
});
$(document).ready(function(){
    $("button").click(function(){
        $("#btnYash").hide();
    })
})